

def swissgermanise(userInput):
    schwiitzerDütsch = userInput
    schwiitzerDütsch = schwiitzerDütsch.replace("verbessern", "verbessere")
    schwiitzerDütsch = schwiitzerDütsch.replace("aussieht", "ousgse")
    schwiitzerDütsch = schwiitzerDütsch.replace("ausieht", "ousgse")
    schwiitzerDütsch = schwiitzerDütsch.replace("brauche", "bruuch")
    schwiitzerDütsch = schwiitzerDütsch.replace("sieht", "gseht")
    schwiitzerDütsch = schwiitzerDütsch.replace("kann ich", "chani")
    schwiitzerDütsch = schwiitzerDütsch.replace("kannst du", "chasch")
    schwiitzerDütsch = schwiitzerDütsch.replace("kannst", "chasch")
    schwiitzerDütsch = schwiitzerDütsch.replace("schweiz", "schwiiz")
    schwiitzerDütsch = schwiitzerDütsch.replace("deutsch", "dütsch")
    schwiitzerDütsch = schwiitzerDütsch.replace("willst du", "wetsch")
    schwiitzerDütsch = schwiitzerDütsch.replace("willst", "wetsch")
    schwiitzerDütsch = schwiitzerDütsch.replace("will ich", "wetti")
    schwiitzerDütsch = schwiitzerDütsch.replace("jetzt", "jitz")
    schwiitzerDütsch = schwiitzerDütsch.replace("einfach", "eifach")
    schwiitzerDütsch = schwiitzerDütsch.replace("hilf", "höuf")
    schwiitzerDütsch = schwiitzerDütsch.replace("verbessern", "verbessere")
    schwiitzerDütsch = schwiitzerDütsch.replace("geht", "geit")
    schwiitzerDütsch = schwiitzerDütsch.replace("schon", "scho")
    schwiitzerDütsch = schwiitzerDütsch.replace("gutes", "guets")
    schwiitzerDütsch = schwiitzerDütsch.replace("gut", "guet")
    schwiitzerDütsch = schwiitzerDütsch.replace("siehst du", "gsesch")
    schwiitzerDütsch = schwiitzerDütsch.replace("ich sehe es", "i gsess")
    schwiitzerDütsch = schwiitzerDütsch.replace("ich sehe", "i gse")
    schwiitzerDütsch = schwiitzerDütsch.replace("sehen", "gse")
    schwiitzerDütsch = schwiitzerDütsch.replace("machst du", "machsch")
    schwiitzerDütsch = schwiitzerDütsch.replace("marienkäfer", "Hemmugüegli")
    schwiitzerDütsch = schwiitzerDütsch.replace("bauch", "ranzä")
    schwiitzerDütsch = schwiitzerDütsch.replace("kopf", "grind")
    schwiitzerDütsch = schwiitzerDütsch.replace("fuss", "scheichä")
    schwiitzerDütsch = schwiitzerDütsch.replace("leute", "lüüt")
    schwiitzerDütsch = schwiitzerDütsch.replace("zeit", "ziit")
    schwiitzerDütsch = schwiitzerDütsch.replace("gib es", "gibs")
    schwiitzerDütsch = schwiitzerDütsch.replace("gibt es", "gits")
    schwiitzerDütsch = schwiitzerDütsch.replace("sprechen", "redä")
    schwiitzerDütsch = schwiitzerDütsch.replace("sprich", "redt")
    schwiitzerDütsch = schwiitzerDütsch.replace("essen", "ässe")
    schwiitzerDütsch = schwiitzerDütsch.replace("der", "dr")
    schwiitzerDütsch = schwiitzerDütsch.replace("die ", "d'")
    schwiitzerDütsch = schwiitzerDütsch.replace("das ", "ds")
    schwiitzerDütsch = schwiitzerDütsch.replace("ist ", "isch ")
    schwiitzerDütsch = schwiitzerDütsch.replace("nicht", "niid")
    schwiitzerDütsch = schwiitzerDütsch.replace("er ", "är ")
    schwiitzerDütsch = schwiitzerDütsch.replace("sie", "se")
    schwiitzerDütsch = schwiitzerDütsch.replace("nach", "nachä")
    schwiitzerDütsch = schwiitzerDütsch.replace("habe", "ha")
    schwiitzerDütsch = schwiitzerDütsch.replace("ich ", "i ")
    schwiitzerDütsch = schwiitzerDütsch.replace("arbeiten", "schaffe")
    schwiitzerDütsch = schwiitzerDütsch.replace("müde", "müed")
    schwiitzerDütsch = schwiitzerDütsch.replace("viel", "feü")
    schwiitzerDütsch = schwiitzerDütsch.replace("euer", "üür")
    schwiitzerDütsch = schwiitzerDütsch.replace("kann", "cha")
    schwiitzerDütsch = schwiitzerDütsch.replace("dir", "dr")
    return(schwiitzerDütsch)



while 1:
    normalesDeutsch = input("Normales deutsch: ")
    print(swissgermanise(normalesDeutsch))

