import time
import keyboard

"""
text = ["We're no strangers to love", "You know the rules and so do I", "A full commitment's what I'm thinking of", "You wouldn't get this from any other guy", "I just wanna tell you how I'm feeling", "Gotta make you understand", "Never gonna give you up", "Never gonna let you down", "Never gonna run around and desert you", "Never gonna make you cry", "Never gonna say goodbye", "Never gonna tell a lie and hurt you", "We've known each other for so long", "Your heart's been aching, but", "You're too shy to say it", "Inside, we both know what's been going on", "We know the game and we're gonna play it", "And if you ask me how I'm feeling", "Don't tell me you're too blind to see", "Never gonna give you up", "Never gonna let you down", "Never gonna run around and desert you", "Never gonna make you cry", "Never gonna say goodbye", "Never gonna tell a lie and hurt you", "Never gonna give you up", "Never gonna let you down", "Never gonna run around and desert you", "Never gonna make you cry", "Never gonna say goodbye", "Never gonna tell a lie and hurt you", "(Ooh, give you up)", "(Ooh, give you up)", "Never gonna give, never gonna give", "(Give you up)", "Never gonna give, never gonna give", "(Give you up)", "We've known each other for so long", "Your heart's been aching, but", "You're too shy to say it", "Inside, we both know what's been going on", "We know the game and we're gonna play it", "I just wanna tell you how I'm feeling", "Gotta make you understand", "Never gonna give you up", "Never gonna let you down", "Never gonna run around and desert you", "Never gonna make you cry", "Never gonna say goodbye", "Never gonna tell a lie and hurt you", "Never gonna give you up", "Never gonna let you down", "Never gonna run around and desert you", "Never gonna make you cry", "Never gonna say goodbye", "Never gonna tell a lie and hurt you", "Never gonna give you up", "Never gonna let you down", "Never gonna run around and desert you", "Never gonna make you cry", "Never gonna say goodbye", "Never gonna tell a lie and hurt you"]
"""
text = ["Giving up on love", "Giving up on love", "I was so crazy about you, everyone knew", "I couldn't sleep when I found out, yeah", "You feel the way you do", "So maybe it's my turn now", "To show you how I feel", "So listen to what I say", "'Cos these feelings I can't conceal", "I'm giving up on love", "'Cos I've been hurt before", "Giving up on love", "And I don't want you no more", "I'm giving up on love", "'Cos I've been hurt before", "Giving up on love", "And I don't want you no more", "I don't believe that you need me", "So don't say you do", "There ain't no reason for staying", "We both know we are through", "So don't try to stop me now", "'Cos all we had has gone", "(All we had has gone)", "So listen to what I say", "'Cos these feelings are oh so strong", "I'm giving up on love", "'Cos I've been hurt before", "Giving up on love", "And I don't want you no more", "I'm giving up on love", "'Cos I've been hurt before", "Giving up on love", "And I don't want you no more", "Giving up, giving up, giving up on love", "Giving up, giving up, giving up on love", "Giving up, giving up, giving up on love", "Giving up, giving up, giving up on love", "So don't try to stop me now", "'Cos all we had has gone", "(All we had has gone)", "So listen to what I say", "'Cos these feelings are oh so strong"]


time.sleep(1)
for i in text:
    keyboard.wait('Delete')
    keyboard.write(i)
    time.sleep(0.1)
    keyboard.press("Enter")
    time.sleep(0.1)
    keyboard.release("Enter")
